# TUGAS
## Pengenalan Array dengan Numpy

Kelompok 4
1. Ircham Machbubi Sholih
2. Andhika Rivai
3. Ahmad Raffi Alhadipuro
4. Achmad Bimo Mulyo
5. Muhammad Rizky Baidlowi




In [3]:
# Buat matriks (arr) dengan tipe data integer 64
arr = [[1, 2, 3],
       [5, 6, 7]]

# Cetak matriks
print("Matriks (arr):")
for row in arr:
    print(row)

# Cetak bentuk (shape) matriks
num_rows = len(arr)
num_cols = len(arr[0])
print("Bentuk (shape) matriks: {}x{}".format(num_rows, num_cols))

# Cetak tipe data matriks
data_type = type(arr[0][0])
print("Tipe data matriks: {}".format(data_type))


Matriks (arr):
[1, 2, 3]
[5, 6, 7]
Bentuk (shape) matriks: 2x3
Tipe data matriks: <class 'int'>


In [4]:
import numpy as np

# Buat matriks (arr_rdm) dengan NumPy dengan nilai acak
arr_rdm = np.random.randint(0, 100, size=(2, 3), dtype=np.int64)

# Cetak matriks
print("Matriks (arr_rdm):\n", arr_rdm)

# Cetak bentuk (shape) matriks
print("Bentuk (shape) matriks:", arr_rdm.shape)

# Cetak tipe data matriks
print("Tipe data matriks:", arr_rdm.dtype)


Matriks (arr_rdm):
 [[ 9 36 23]
 [17 64 92]]
Bentuk (shape) matriks: (2, 3)
Tipe data matriks: int64


# Aritmatika Dasar dengan Numpy

In [5]:
import numpy as np

# Membuat matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Membuat matriks arr_rdm
arr_rdm = np.random.randint(0, 100, size=(2, 3), dtype=np.int64)

# Penjumlahan arr dan arr_rdm
addition_result = arr + arr_rdm
print("Penjumlahan arr dan arr_rdm:\n", addition_result)

# Pengurangan arr dan arr_rdm
subtraction_result = arr - arr_rdm
print("Pengurangan arr dan arr_rdm:\n", subtraction_result)

# Perpangkatan dua elemen-elemen arr_rdm
power_result = arr_rdm ** 2
print("Perpangkatan dua elemen arr_rdm:\n", power_result)

# Perkalian elemen-wise arr dan arr_rdm
elementwise_mult_result = arr * arr_rdm
print("Perkalian elemen-wise arr dan arr_rdm:\n", elementwise_mult_result)

# Transpose matriks arr_rdm
arr_rdm_transpose = np.transpose(arr_rdm)
print("Transpose matriks arr_rdm:\n", arr_rdm_transpose)

# Operasi perkalian matriks arr dan arr_rdm
matrix_mult_result = np.dot(arr, arr_rdm_transpose)
print("Perkalian matriks arr dan arr_rdm:\n", matrix_mult_result)


Penjumlahan arr dan arr_rdm:
 [[35 16 45]
 [86 13 49]]
Pengurangan arr dan arr_rdm:
 [[-33 -12 -39]
 [-76  -1 -35]]
Perpangkatan dua elemen arr_rdm:
 [[1156  196 1764]
 [6561   49 1764]]
Perkalian elemen-wise arr dan arr_rdm:
 [[ 34  28 126]
 [405  42 294]]
Transpose matriks arr_rdm:
 [[34 81]
 [14  7]
 [42 42]]
Perkalian matriks arr dan arr_rdm:
 [[188 221]
 [548 741]]


In [6]:
import numpy as np

# Membuat matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Mencetak nilai rata-rata arr
average_arr = np.mean(arr)
print("Nilai rata-rata arr: ", average_arr)

# Mencetak nilai rata-rata per baris arr
average_per_row = np.mean(arr, axis=1)
print("Nilai rata-rata per baris arr: ", average_per_row)

# Mencetak total nilai seluruh elemen matriks arr
total_sum = np.sum(arr)
print("Total nilai seluruh elemen matriks arr: ", total_sum)

# Mencetak nilai maksimal per kolom matriks arr
max_per_column = np.max(arr, axis=0)
print("Nilai maksimal per kolom matriks arr: ", max_per_column)


Nilai rata-rata arr:  4.0
Nilai rata-rata per baris arr:  [2. 6.]
Total nilai seluruh elemen matriks arr:  24
Nilai maksimal per kolom matriks arr:  [5 6 7]


# Fitur pada Numpy

In [7]:
import numpy as np

# Membuat array arrg dengan nilai rentang 1 hingga 20
arrg = np.arange(1, 21)

# Mencetak array arrg
print("Array arrg:", arrg)

# Mencetak nilai arrg pada indeks 5
index_5 = arrg[5]
print("Nilai arrg pada indeks 5:", index_5)

# Mencetak nilai arrg untuk 3 elemen dari terakhir
last_3_elements = arrg[-3:]
print("Nilai arrg untuk 3 elemen dari terakhir:", last_3_elements)

# Mencetak nilai arrg dari indeks 3 hingga 6 (indeks 3, 4, 5, 6)
range_3_to_6 = arrg[3:7]
print("Nilai arrg dari indeks 3 hingga 6:", range_3_to_6)


Array arrg: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Nilai arrg pada indeks 5: 6
Nilai arrg untuk 3 elemen dari terakhir: [18 19 20]
Nilai arrg dari indeks 3 hingga 6: [4 5 6 7]


In [8]:
import numpy as np

# Membuat matriks arr
arr = np.array([[1, 2, 3], [5, 6, 7]], dtype=np.int64)

# Mencetak matriks arr
print("Matriks arr:\n", arr)

# Mengambil slice matriks arr dengan output [[2 3] [6 7]]
slice1 = arr[:, 1:]
print("Slice matriks arr dengan output:\n", slice1)

# Mengambil slice matriks arr dengan output [[3] [7]]
slice2 = arr[:, 2:3]
print("Slice matriks arr dengan output:\n", slice2)


Matriks arr:
 [[1 2 3]
 [5 6 7]]
Slice matriks arr dengan output:
 [[2 3]
 [6 7]]
Slice matriks arr dengan output:
 [[3]
 [7]]


In [9]:
import numpy as np

# Membuat matriks mtx_rdm 3x4 dengan nilai acak
mtx_rdm = np.random.randint(0, 100, size=(3, 4), dtype=np.int64)

# Mencetak bentuk (shape) awal matriks mtx_rdm
print("Bentuk (shape) awal mtx_rdm:", mtx_rdm.shape)

# Mengubah shape mtx_rdm menjadi satu dimensi
mtx_rdm_flat = mtx_rdm.flatten()
print("Matriks mtx_rdm dalam satu dimensi:\n", mtx_rdm_flat)

# Mengubah shape mtx_rdm menjadi 6x2
mtx_rdm_reshaped = mtx_rdm.reshape(6, 2)
print("Matriks mtx_rdm dengan bentuk 6x2:\n", mtx_rdm_reshaped)


Bentuk (shape) awal mtx_rdm: (3, 4)
Matriks mtx_rdm dalam satu dimensi:
 [90 78 49 14 32 62 77 63 74 79 55 80]
Matriks mtx_rdm dengan bentuk 6x2:
 [[90 78]
 [49 14]
 [32 62]
 [77 63]
 [74 79]
 [55 80]]
